// This file was automatically generated by "C:\Users\Joe\Desktop\GripGrasp Development\ExportGripGraspDevelopment.bat". 
char *GripGraspSourceRelease = "Development post Bedrest 3.1 (2017-09-12 15h39m43s)"; 
