// This file was automatically generated by "C:\Users\Joe\Desktop\GripGrasp Development\ExportGripGraspDevelopment.bat". 
char *GripGraspSourceRelease = "Development post Bedrest 3.4 (2017-09-27 15h36m38s)"; 
