// This file was automatically generated by "C:\Users\Joe\Desktop\GripGrasp Development\ExportGripGraspDevelopment.bat". 
char *GripGraspSourceRelease = "Development post Bedrest 3.3 (2017-09-21 03h08m18s)"; 
